support subscription-manager release lock
RedHatInsights/inventory-schemas pull request #18
Opened 2020-09-25 07:46 UTC by MichaelMraka

added rhsm_releasever to support for subscription-manager release lock

2020-09-25 15:25 UTC, shdunning commented
@MichaelMraka need to add `description` and `example` to your new field.

2020-09-25 15:26 UTC, shdunning requested changes

2020-09-25 15:26 UTC, shdunning commented on schemas/system_profile/v1.yaml
> +      rhsm_releasever:
Need to add `description` and `example`.

```
JSON Schema detected
JSON Schema (loose) detected
JSON Schema Draft 7 detected
 
/tmp/workspace/inventory-schemas_PR-18/schemas/system_profile/v1.yaml
250:23 error property-description #/$defs/SystemProfile/properties/rhsm_releasever does not define description
250:23 error property-example #/$defs/SystemProfile/properties/rhsm_releasever does not define an example
 
2 problems (2 errors, 0 warnings, 0 infos, 0 hints) 
script returned exit code 1
```

2020-09-30 11:56 UTC, MichaelMraka commented on schemas/system_profile/v1.yaml
> +      rhsm_releasever:
comment and example fixed

2020-09-30 12:27 UTC, jharting requested changes

2020-09-30 12:27 UTC, jharting commented on schemas/system_profile/v1.yaml
> +        description: Sytem release version set by subscription-manager
Sytem

2020-09-30 12:27 UTC, jharting commented on schemas/system_profile/v1.yaml
> +        example: "8.2"
Does subscription-manager always follow the `major.minor` format? If the output is well-defined I wonder if we can specify it here with a regex

2020-10-01 09:16 UTC, MichaelMraka commented on schemas/system_profile/v1.yaml
> +        example: "8.2"
No, it can be "8", "8.0", "8.1", ... or empty (""). Or it might not be even set (IMHO majority of the cases).

2020-10-01 09:18 UTC, MichaelMraka commented on schemas/system_profile/v1.yaml
> +        description: Sytem release version set by subscription-manager
fixed typo

2020-11-05 09:10 UTC, MichaelMraka commented
Rebased to current master and squashed fixes into a single commit.

2020-12-02 18:59 UTC, iphands commented
@MichaelMraka  I *think* this is unneeded after we merged https://github.com/RedHatInsights/inventory-schemas/pull/27
Closing please do open if you think this is incorrect.

2020-12-02 18:59 UTC, closed without merging