Adding more lint - RHCLOUD-8254
RedHatInsights/inventory-schemas pull request #19
Opened 2020-09-28 21:00 UTC by tahmidefaz

2020-09-29 12:48 UTC, tahmidefaz commented
Lmk, if you think we should add any more lint, atm!

2020-09-29 13:32 UTC, kruai approved these changes
LGTM!

2020-09-30 12:25 UTC, jharting commented on schemas/system_profile/v1.yaml
> +          maxLength: 15
This is potentially a breaking change. (Even though it looks unlikely we saw reporters sending unexpected stuff in the past). It would be better to split this into linter PR (where linter violations caused by existing definitions are suppressed by the exclusion list) and a follow-up PR where these are addressed (after verifying that the change does not break existing reporters).

2020-09-30 12:42 UTC, tahmidefaz commented on schemas/system_profile/v1.yaml
> +          maxLength: 15
:lion: :tiger: :bear: :open_mouth:

2020-09-30 12:50 UTC, thearifismail approved these changes

2020-10-01 15:59 UTC, rafaelcassau commented on .spectral.yaml
> +        match: '^[A-Z]+\s*\S+(?:\s+\S+){2,}\s*$'
```suggestion
        match: '^[A-Z]*\s*\S+(?:\s+\S+){2,}\s*$'
```
In this case the expression `A valid expression` will fail because of `^[A-Z]+` because it requires one more character, to work properly you can replace `+` by `*`, in this case `+` means one or more while `*` means zero or more.

2020-10-01 20:41 UTC, rafaelcassau approved these changes
LGTM

2020-10-02 18:01 UTC, tahmidefaz commented
@ryandillinfelton added `package.json` like you suggested.

2020-10-02 18:09 UTC, ryandillinfelton requested changes
Just another change to the dang regex. But looks/works great otherwise

2020-10-02 18:15 UTC, rafaelcassau commented on .spectral.yaml
> +        match: '^[A-Z]*\s*\S+(?:\s+\S+){2,}\s*$'
it's a good improvement

2020-10-02 18:16 UTC, tahmidefaz commented on .spectral.yaml
> +        match: '^[A-Z]*\s*\S+(?:\s+\S+){2,}\s*$'
Just updated the regex like you suggested. Thanks a lot! :+1:

2020-10-02 18:18 UTC, ryandillinfelton approved these changes
LGTM :rocket:

2020-10-02 18:18 UTC, merged