Defining the manual process for approving PRs
RedHatInsights/inventory-schemas pull request #23
Opened 2020-10-05 21:15 UTC by tahmidefaz

Let me know what we need to add/update

2020-10-06 14:40 UTC, kruai requested changes
Looks great! Thanks for typing all this out - I just have a few suggestions that would make things a bit more readable.

2020-10-06 14:40 UTC, kruai commented on README.md
> +2. The person from HBI team will analyze the data returned from the App-SRE job and produce a report similiar to to the following and post it in the pull request thread.
```suggestion
2. The HBI team member will analyze the data returned from the App-SRE job, produce a report similar to to the following, and post it in the pull request thread.
```
Change run-on sentence and fix typo

2020-10-06 14:40 UTC, kruai commented on README.md
> +3. If the report seems satisfactory and if there are no more concerns, someone from the HBI team will merge the PR.
```suggestion
3. If the report seems satisfactory and there are no more concerns, someone from the HBI team will merge the PR.
```
I'm actually not sure about this one, but it sounds more natural to me? You can leave it in if you disagree :)

2020-10-06 14:40 UTC, kruai commented on README.md
> +4. However, in the event that the report is unsatisfactory, e.g. a high number of failures from one or multiple reporters, coordination must happen between the person who opened the PR, the HBI team
```suggestion
4. In the event that the report is unsatisfactory (e.g. it shows a high number of failures from one or multiple reporters), the PR owner must coordinate with the HBI team and the stakeholders from the reporter(s) that show failures. Together, they must decide whether to change the PR or to update the reporter(s).
```
I changed some things around to remove passive voice and (hopefully) improve readability

2020-10-06 14:40 UTC, kruai commented on README.md
> +5. If the pull request was opened to add a new field rather than update a pre-existing one, no report like the one above needs to be generated and someone from the HBI team can merge it if there are
```suggestion
5. If the pull request was opened to add a new field rather than update a pre-existing one, no report like the one above needs to be generated; someone from the HBI team can merge it if there are no concerns.
```
I divided up the thoughts with a semicolon because it was running on a bit. If you prefer, you can use a period and separate it into two sentences instead.

2020-10-06 14:40 UTC, kruai commented on README.md
> +6. Once a PR to update the system profile schema is merged, the representative from the HBI team who merged the PR can go ahead and open a PR in the HBI repository to reflect those changes if no such
```suggestion
6. Once the PR is merged, the HBI team member who merged it can open another PR in the HBI repository to reflect those changes.
```
Removes some redundancy for clarity's sake. I'm also suggesting we remove that final clause because I feel it's implied... what do you think?

2020-10-06 14:40 UTC, kruai commented on README.md
>  - [ ] Write more to do items
LOL

2020-10-15 13:21 UTC, kruai approved these changes

2020-10-21 22:53 UTC, gmcculloug reviewed
@tahmidefaz Overall this is in good shape.  I had one comment to reword an item and along with that wanted to suggest that instead of referencing "HBI team" that we refer to "repository maintainers" for most of them.  The one exclusion would be item 6 which is truly referencing work that would happen in the HBI repo.

Thoughts?

2020-10-21 22:53 UTC, gmcculloug commented on README.md
> +5. If the pull request was opened to add a new field rather than update a pre-existing one, no report like the one above needs to be generated. Someone from the HBI team can merge it if there are no
@tahmidefaz What do you think of something like this:
If the pull request only adds new fields there is no need to generate a report since the database will not contain values to compare against for the new fields.  A repository maintainer will help in getting consensus with the schema [Stakeholders](#stakeholders) before merging the PR.

If you want we could also link the "repository maintainer" to the github team.

2020-10-22 13:09 UTC, tahmidefaz commented on README.md
> +5. If the pull request was opened to add a new field rather than update a pre-existing one, no report like the one above needs to be generated. Someone from the HBI team can merge it if there are no
Yes, sounds good. I will update it. Thanks! :+1:

2020-10-22 13:31 UTC, tahmidefaz commented
@gmcculloug just updated it with your suggestions :+1:

2020-10-22 14:22 UTC, gmcculloug approved these changes

2020-10-22 14:23 UTC, merged