Add additional sap facts
RedHatInsights/inventory-schemas pull request #25
Opened 2020-10-13 14:59 UTC by CodeHeeler

2020-10-13 15:04 UTC, CodeHeeler commented
Puptoo PR here: https://github.com/RedHatInsights/insights-puptoo/pull/72

2020-10-13 17:41 UTC, kruai approved these changes

2020-10-13 21:25 UTC, gmcculloug commented on schemas/system_profile/v1.yaml
> +      sap_version_info:
@CodeHeeler Is there a reason to include "_info" in this key name?  Is it following some existing pattern?

This schema file current has: `bios_version`, `os_kernel_version`, `insights_client_version`, and `insights_egg_version`.

Could this key be reduced to `sap_version`?

2020-10-13 21:32 UTC, jeromemarc commented on schemas/system_profile/v1.yaml
> +      sap_version_info:
Let's keep it consistent with other fact names. Let's go with `sap_version`.

2020-10-13 21:36 UTC, CodeHeeler commented on schemas/system_profile/v1.yaml
> +      sap_version_info:
Was following @jeromemarc's lead and that was how it was initially described.  Just pushed up the change to the new shorter name now.

2020-10-21 16:10 UTC, iphands commented
@CodeHeeler would we rather make this an integer type?
Its probably much faster to parse if it is.

Is FE, A2. D8 ever supported?

2020-10-21 16:16 UTC, CodeHeeler commented
> @CodeHeeler would we rather make this an integer type?
> Its probably much faster to parse if it is.

Sure, I'll update it to integer.

> Is FE, A2. D8 ever supported?

Not sure what this means? ^

2020-10-21 18:22 UTC, tahmidefaz requested changes

2020-10-21 18:22 UTC, tahmidefaz commented on schemas/system_profile/v1.yaml
> +        pattern: '(?!99)(?!98)^[0-9]{2}$'
since this is an integer now, I think using `maximum` and `minimum` would be ideal here instead of `maxLength`. You also won't need the `pattern` anymore.

2020-10-21 18:38 UTC, CodeHeeler commented on schemas/system_profile/v1.yaml
> +        pattern: '(?!99)(?!98)^[0-9]{2}$'
Actually now that I think about it and look back at the spec, what about 00, 01, 02, etc?  Comparisons won't change, but is there any use case for wanting that leading zero included instead of using only an integer?

2020-10-21 18:41 UTC, CodeHeeler commented on schemas/system_profile/v1.yaml
> +        pattern: '(?!99)(?!98)^[0-9]{2}$'
See this source: https://help.sap.com/viewer/2c1988d620e04368aa4103bf26f17727/2.0.05/en-US/ae305ab18bad42efa7b067e7cc82b846.html

2020-10-21 19:37 UTC, iphands commented on schemas/system_profile/v1.yaml
> +        pattern: '(?!99)(?!98)^[0-9]{2}$'
WAIT, if 00 - 09 are valid, has to be String again right? (thanks Dana :D)

2020-10-21 20:00 UTC, ryandillinfelton approved these changes

2020-10-21 20:04 UTC, tahmidefaz approved these changes

2020-10-21 20:30 UTC, gmcculloug commented on schemas/system_profile/v1.yaml
> +        example: '42'
@CodeHeeler For clarify maybe add the constraint to the description:
```yaml
description: The instance number of the SAP HANA system (must be a two-digit number between 00 and 97)
```

Also, the example value could be extended to show a leading-zero value in addition to `03 or 42`.

2020-10-21 20:39 UTC, CodeHeeler commented on schemas/system_profile/v1.yaml
> +        example: '42'
Done. :)

2020-10-22 14:10 UTC, merged