Combining #9 and #26 splitting os release and adding os vendor flavor etc
RedHatInsights/inventory-schemas pull request #27
Opened 2020-10-23 20:55 UTC by iphands

Do we want to do something more like this? instead of #26 and #9 

@jharting do you think flatter is better for searching
cc @gmcculloug on the searching thing

2020-10-23 20:58 UTC, iphands commented
cc @ShimShtein

2020-10-25 09:26 UTC, ShimShtein commented
Sounds good, but I am a bit worry about enforcing enums. There always be someone with an exotic linux distro, and it looks like we won't want to reject the whole host because of this.

2020-10-26 12:24 UTC, jharting commented
@iphands more nesting means longer filter queries (e.g. `?filter[system_profile][operating_system][major][gte]=7`) which is not a a big deal, though

2020-10-26 13:41 UTC, iphands commented
> Sounds good, but I am a bit worry about enforcing enums. There always be someone with an exotic linux distro, and it looks like we won't want to reject the whole host because of this.

I think we do actually. We are specifically *not* aiming to open the Inventory to dump random host info into.
If there is not a business case for storing the data, we should drop.

2020-10-29 22:06 UTC, beav approved these changes

2020-10-29 22:21 UTC, CodeHeeler approved these changes
LGTM

2020-11-02 18:49 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        maxLength: 4
minor nitpick, but maxLength feels redundant if we're enforcing an enum

2020-11-03 01:54 UTC, iphands commented on schemas/system_profile/v1.yaml
> +        maxLength: 4
WFM to remove I had seen another example somewhere else I think.

2020-11-03 01:55 UTC, iphands commented on schemas/system_profile/v1.yaml
> +        maxLength: 4
Or maybe even the linter complains. Lemme see

2020-11-03 12:05 UTC, CodeHeeler commented on schemas/system_profile/v1.yaml
> +        maxLength: 4
Yep, you're right, the linter does not like it if you do not include maxLength.

2020-11-03 21:20 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        maxLength: 4
Dang. We can just leave it in for now, it's not a big deal. @tahmidefaz I think we may want to adjust the linter a bit to account for stuff like this.

2020-11-03 21:28 UTC, tahmidefaz commented on schemas/system_profile/v1.yaml
> +        maxLength: 4
Yeah, it's doable :+1:

2020-11-04 19:56 UTC, ryandillinfelton approved these changes
This looks good to me

2020-11-04 19:56 UTC, tahmidefaz requested changes

2020-11-04 19:56 UTC, tahmidefaz commented on schemas/system_profile/v1.yaml
> +        maxLength: 4
Correct me if I am wrong, but, since `major` and `minor` are both `integer`s I think we should use `maximum` and `minimum`, yeah? I don't think `maxLength` doesn't do anything for type `integer`. :disappointed:

2020-11-04 20:02 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        maxLength: 4
Nope you're right. Good catch!

2020-11-11 19:14 UTC, beav commented on schemas/system_profile/v1.yaml
> +        maxLength: 4
@iphands Can you take a look at ^^ ? I think this is the last open comment

2020-11-11 20:46 UTC, iphands commented on schemas/system_profile/v1.yaml
> +        maxLength: 4
That wfm

2020-11-11 20:57 UTC, beav commented
lgtm as well

2020-11-16 14:16 UTC, beav commented
@tahmidefaz I think the PR is current at this point. can you take a look and re-review?

2020-11-16 14:36 UTC, tahmidefaz commented
@beav Sorry, our team was doing a hackathon the last sprint. Taking a look now! :+1:

2020-11-16 14:45 UTC, tahmidefaz approved these changes
LGTM :+1:

2020-11-16 14:46 UTC, merged