Add sap_local_instances fact
RedHatInsights/inventory-schemas pull request #3
Opened 2020-07-24 01:43 UTC by CodeHeeler

2020-07-24 06:39 UTC, jharting commented
@CodeHeeler please add a description of the new field and ideally also an example value. Are there any constraints that should be validated on array items besides them being strings?

2020-07-29 10:32 UTC, Glutexo commented
May I ask for a source for this new field? Where was it added to the payload?

2020-07-29 13:56 UTC, beav commented
It was added in puptoo in https://github.com/RedHatInsights/insights-puptoo/blob/master/src/puptoo/process.py#L125-L127, along with the `sap_system` field.

re: constraints, we are working on gathering the max length and examples. I don't expect there to be more than a handful of strings in the array, with each string being less than 100-200 char.

2020-07-30 08:07 UTC, Glutexo commented
Thanks! Would you add that to the specification together with a description?

2020-09-03 21:10 UTC, CodeHeeler commented
> Thanks! Would you add that to the specification together with a description?

Added description, example, maxLength, and pattern/regex based on https://help.sap.com/viewer/2c1988d620e04368aa4103bf26f17727/2.0.05/en-US/7672838aa9c44c7ab9d10188531669f3.html

2020-09-04 12:48 UTC, beav approved these changes

2020-09-07 08:10 UTC, jharting requested changes
@CodeHeeler @beav are you sure about the format? Here are a few examples of what puptoo is sending: (HDB00, HDB10, SCS02, SMDA98)

cc @SteveHNH

2020-09-07 12:25 UTC, beav commented
@jharting good catch. it looks like there are two different attributes we are conflating.

There is the `local_instances`, which are the instances that are running on the server. These are not the SIDs.

We probably need to rename this field to `sap_sids`. The validation should stay the same.

I think in Puptoo, it should do something like `profile["sap_sids"] = [sap.sid(instance) for instance in local_instances]` (untested pseudocode).

2020-09-08 16:49 UTC, beav commented
Here is what I have with the proposed puptoo change:

```
'sap_system': True,
'sap_sids': ['RHE']
```

Most systems will only have one SID, but its possible to have multiple.

2020-09-08 16:54 UTC, beav commented
https://github.com/RedHatInsights/insights-puptoo/pull/67

It's OK to merge the puptoo PR before any inventory change. Extra fields are ignored by inventory svc.

2020-09-08 17:22 UTC, beav commented
related: https://github.com/RedHatInsights/insights-host-inventory/pull/709

2020-09-11 07:57 UTC, Glutexo approved these changes
I can approve like this, but I’d consider adding the _minLength_ constraint. Also please take a look at my last [comment](https://github.com/RedHatInsights/insights-host-inventory/pull/709#issuecomment-690938713) for https://github.com/RedHatInsights/insights-host-inventory/pull/709. We need the regex validation in Marshmallow too.

2020-09-11 07:57 UTC, Glutexo commented on schemas/system_profile/v1.yaml
> +          example: "H2O"
Is this an example of a real value? 😃

2020-09-11 07:57 UTC, Glutexo commented on schemas/system_profile/v1.yaml
> +          maxLength: 3
This is slightly redundant, because the _pattern_ already demands a string of an exact length of 3 characters. For consistency we could even add `minLength: 3`.

2020-09-11 13:56 UTC, CodeHeeler commented on schemas/system_profile/v1.yaml
> +          example: "H2O"
heh, I had no examples of real values at that time, but since it only demands the first character be a letter, and the subsequent two can be digits or letters, it's actually a possible real value. :)

2020-09-11 13:57 UTC, CodeHeeler commented on schemas/system_profile/v1.yaml
> +          maxLength: 3
The pattern will handle everything, but it seemed we generally added maxLength in the schema, so I put it there for ease of folks glancing through the code to instantly know the space these are taking up rather than having to parse the regex to figure it out.  I don't see why we should also add the minLength, but I am happy to do so if you'd prefer.

2020-09-11 14:01 UTC, CodeHeeler commented
> I can approve like this, but I’d consider adding the _minLength_ constraint. Also please take a look at my last [comment](https://github.com/RedHatInsights/insights-host-inventory/pull/709#issuecomment-690938713) for [RedHatInsights/insights-host-inventory#709](https://github.com/RedHatInsights/insights-host-inventory/pull/709). We need the regex validation in Marshmallow too.

What is Marshmallow?  Where is the repo for that?  Was this comment meant for @beav or do you know which team owns Marshmallow so that I have a contact on this work?  Thanks!

2020-09-14 08:27 UTC, jharting approved these changes

2020-09-14 08:35 UTC, merged