add owner_id field [RHCLOUD-8583]
RedHatInsights/inventory-schemas pull request #30
Opened 2020-12-01 14:55 UTC by ryandillinfelton

Mirror of changes needed for https://github.com/RedHatInsights/insights-host-inventory/pull/747/files.
Adds a new field to the sytem profile `owner_id` which is validated as a UUID

2020-12-01 15:02 UTC, kruai approved these changes

2020-12-01 15:02 UTC, tahmidefaz requested changes

2020-12-01 15:02 UTC, tahmidefaz commented on schemas/system_profile/v1.yaml
> +        pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
Can we have an example of how an `owner_id` might look like?

2020-12-01 15:16 UTC, kruai commented on schemas/system_profile/v1.yaml
> +        pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
Good point, Tahmid... That would make a good reference, and help out the regex-impaired (like me)

2020-12-01 16:40 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
Added an example and a description

2020-12-01 16:50 UTC, tahmidefaz commented
@ryandillinfelton for some reason the pr check isn't working for this repo. I had some doubts, so I decided to run the lint check locally on my laptop, and I got:
`153:16  error  property-string-max-length  #/$defs/SystemProfile/properties/owner_id does not define max length`

2020-12-01 20:44 UTC, thearifismail approved these changes

2020-12-02 14:30 UTC, closed without merging

2020-12-02 14:32 UTC, ryandillinfelton commented
Looks like the test is still busted. Closing and reopening [here](https://github.com/RedHatInsights/inventory-schemas/pull/34) to switch the check.