Add the model name as cpu_model to system profile
RedHatInsights/inventory-schemas pull request #44
Opened 2021-02-01 20:51 UTC by CodeHeeler

Add the cpu model name as cpu_model to system profile as requested:
https://issues.redhat.com/browse/HBISPSC-39

Related puptoo PR:
https://github.com/RedHatInsights/insights-puptoo/pull/117

2021-02-03 18:36 UTC, iphands requested changes

2021-02-03 18:36 UTC, iphands commented on schemas/system_profile/v1.yaml
> +        max_Length: 100
should be max_length the L is capitalized here

2021-02-11 17:46 UTC, ryandillinfelton approved these changes

2021-02-11 18:18 UTC, kruai approved these changes

2021-02-11 18:34 UTC, tahmidefaz requested changes
@CodeHeeler Sorry, I just got to look at this. Can you provide two very simple examples of valid and invalid `cpu_model` [here](https://github.com/RedHatInsights/inventory-schemas/tree/master/tests/utils)? It will help us with not writing tests in HBI for this specific field.

2021-02-11 23:47 UTC, CodeHeeler commented
@tahmidefaz Ah, thanks!  Done. Will do this in the future for all new facts.

2021-02-12 14:45 UTC, kruai commented
I've dismissed old reviews, as Dana has addressed all the requested changes.

2021-02-12 15:02 UTC, tahmidefaz approved these changes
Awesome! Looks great!! :+1:

2021-02-12 15:46 UTC, ryandillinfelton approved these changes
:+1:

2021-02-12 16:08 UTC, merged