Add gpg_pubkey array
RedHatInsights/inventory-schemas pull request #58
Opened 2021-04-01 16:56 UTC by csams

GPG pubkeys are stored as an array of package names with RPM sorting applied.
The sort probably has no meaning for these synthetic packages, but it makes
order consistent.

Signed-off-by: Christopher Sams <csams@redhat.com>

2021-04-01 18:14 UTC, CodeHeeler approved these changes
LGTM

2021-04-01 18:18 UTC, CodeHeeler commented
Related PRs:
https://github.com/RedHatInsights/insights-host-inventory/pull/857
https://github.com/RedHatInsights/insights-puptoo/pull/145

2021-04-01 19:09 UTC, ryandillinfelton requested changes
I'm requesting changes because we need some `valid` and `invalid` cases added to the test files here: https://github.com/RedHatInsights/inventory-schemas/tree/master/tests/utils. 

I also had a question about if we can tighten up the validation, if not that's fine, I just wanted to check since I'm not all that familiar with the format. Thanks!

2021-04-01 19:09 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +          maxLength: 512
How specific is the GPG public key format? Would it be possible to make this more specific?

2021-04-05 13:32 UTC, kruai commented on schemas/system_profile/v1.yaml
> +          maxLength: 512
Also, we should add the field to `valids.py` and `invalids.py`

2021-04-05 13:32 UTC, kruai requested changes

2021-04-05 13:32 UTC, kruai commented on schemas/system_profile/v1.yaml
> +          maxLength: 512
Also, we should add the field to `valids.py` and `invalids.py`

2021-04-07 15:40 UTC, csams commented on schemas/system_profile/v1.yaml
> +          maxLength: 512
The format is basically the same as for other packages. I can infer a bit of structure, but I don't think we gain much by encoding it.

I updated valids/invalids. Thanks for pointing those out!

2021-04-07 17:35 UTC, kruai approved these changes
LGTM!

2021-04-07 17:57 UTC, tahmidefaz approved these changes
Looks good! :+1:

2021-04-07 18:00 UTC, ryandillinfelton approved these changes

2021-04-07 18:00 UTC, merged