Generic filtering
RedHatInsights/inventory-schemas pull request #70
Opened 2021-06-10 20:20 UTC by ryandillinfelton

2021-06-10 20:21 UTC, ryandillinfelton commented
Converting to draft while I update the readme

2021-06-10 22:40 UTC, kruai approved these changes

2021-06-10 22:41 UTC, kruai commented on README.md
> +When contributing a new field to the system_profile schema please insure you complete the following steps:
```suggestion
When contributing a new field to the system_profile schema, please ensure you complete the following steps:
```

2021-06-11 13:36 UTC, tahmidefaz requested changes
Looks good! Just check the lint. I think just capitalizing the first letters of the sentences will fix it.

2021-06-11 13:36 UTC, tahmidefaz commented on schemas/system_profile/v1.yaml
> +        description: the version number of insights client. supports wildcards
Lint is failing because of this line. You need to change it.

2021-06-11 13:57 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        description: the version number of insights client. supports wildcards
All checks passing

2021-06-11 14:05 UTC, kruai approved these changes
LGTM!

2021-06-11 14:13 UTC, tahmidefaz approved these changes
Lookin' good! :+1:

2021-06-11 14:14 UTC, merged