Add deployments from rpm ostree status to system profile.
RedHatInsights/inventory-schemas pull request #71
Opened 2021-06-13 20:48 UTC by csams

Signed-off-by: Christopher Sams <csams@redhat.com>

2021-06-22 18:42 UTC, ryandillinfelton requested changes
Requesting:

- [ ] Stricter checksum validation
- [ ] more invalid examples
- [ ] some cleanup

2021-06-22 18:42 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        example: "63335a77f9853618ba1a5f139c5805e82176a2a040ef5e34d7402e12263af5bb"
Is this hex? We could use regex here to insure that it's valid hex AND specifically 64 characters long.

2021-06-22 18:42 UTC, ryandillinfelton commented on tests/test_schema.py
> +# from openapi_spec_validator import validate_spec
if you don't need this could you delete the whole line please.

2021-06-22 18:42 UTC, ryandillinfelton commented on tests/utils/invalids.py
> +    {"rpm_ostree_deployments": [{  # checksum empty
This testing cold be more thorough. You only verify the checksum validation here.

2021-06-23 11:44 UTC, gmcculloug commented
@beav Can you please review the OSTree properties and structure here and verify it makes sense?

@csams Do you think we'll need to be able to search on any of these properties?

2021-06-27 15:32 UTC, csams commented on tests/test_schema.py
> +# from openapi_spec_validator import validate_spec
Sure, I'll delete it. Tests won't even run with the line, so I'm not sure how anyone is testing this repo with it as-is.

2021-06-27 15:32 UTC, csams commented on schemas/system_profile/v1.yaml
> +        example: "63335a77f9853618ba1a5f139c5805e82176a2a040ef5e34d7402e12263af5bb"
Sounds good.

2021-06-27 15:54 UTC, csams commented on tests/utils/invalids.py
> +    {"rpm_ostree_deployments": [{  # checksum empty
done

2021-06-28 14:13 UTC, csams commented
@gmcculloug We'll need to make the checksum searchable.

2021-06-28 14:47 UTC, beav commented
> @gmcculloug We'll need to make the checksum searchable.

Do you just need "matches first part of string" or full substring?

Like if I had: `1234abc` and `34a777`, if I searched for `34a` would you expect one result or 2 results?

2021-06-29 16:43 UTC, csams commented
@beav @gmcculloug We can defer the search capability for now if it can be added later.

2021-06-29 20:40 UTC, ryandillinfelton approved these changes
looks good now. Thanks Chris!

2021-06-29 20:42 UTC, kruai approved these changes
LGTM

2021-06-29 20:51 UTC, merged