[WIP] Generic filtering xjoin related changes
RedHatInsights/inventory-schemas pull request #78
Opened 2021-09-29 20:06 UTC by ryandillinfelton

Generic filtering for xjoin work has lead to some small changes in how the schema should be. I've updated the schema to be compliant and updated our instructions for contribution to include the new requirements.

The biggest change is the need to provide an example string with 3 different (unless that's impossible) example values for new string fields. This is so that we can automatically populate example hosts in xjoin-search with realistic data for manual and automated tests.

The requirements may still change as test generation work for generic filtering on xjoin is ongoing. Please let me know if there are any concerns around the changes or there are any better ways to insure compliance with the new requirements, especially the example strings.

2022-02-10 20:02 UTC, kruai requested changes

2022-02-10 20:02 UTC, kruai commented on schemas/system_profile/v1.yaml
> -        example: True
examples are required for each field, even if they're boolean, right?

2022-02-10 20:02 UTC, kruai commented on schemas/system_profile/v1.yaml
> +        example: 'edge, not_edge, edge'
`edge` is the only allowed value right now

2022-02-10 20:02 UTC, kruai commented on schemas/system_profile/v1.yaml
> +        example: 'green, red, green'
`green` is listed twice

2022-02-10 20:18 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        pattern: "^([A-Fa-f0-9]{2}[:-]){5}[A-Fa-f0-9]{2}$,^([A-Fa-f0-9]{4}[.]){2}[A-Fa-f0-9]{4}$,^[A-Fa-f0-9]{12}$,^([A-Fa-f0-9]{2}[:-]){19}[A-Fa-f0-9]{2}$,^[A-Fa-f0-9]{40}$"
Nope, switched it back

2022-02-10 20:22 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        example: 'edge, not_edge, edge'
I need some kind of alternative for the sake of testing filtering functionality so for enums with only one option I have to use a fake option. Validity isn't a huge concern since that validation is done on ingestion and doesn't interfere with the filtering test. I suppose it could be misleading to those reading the schema though so I'll look into alternatives.

2022-02-10 20:22 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        example: 'green, red, green'
I understand it's redundant but it's great for the tests.

2022-02-10 20:57 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        example: 'green, red, green'
Changed :+1:

2022-02-10 21:30 UTC, kruai reviewed
Almost ready! Just one more Q

2022-02-11 15:42 UTC, kruai commented on schemas/system_profile/v1.yaml
> +        example: 'edge, edge, edge'
OK. It looks strange, and might be a little weird for end-users, but it's not incorrect. I can go ahead and approve.

2022-02-11 18:02 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        example: 'edge, edge, edge'
I'll look into changing the method's down the line but it will require some modification to the updater script.

2022-02-11 22:01 UTC, thearifismail commented on schemas/system_profile/v1.yaml
> +        example: "00:00:00:00:00:00, 10:00:00:00:00:00, 20:00:00:00:00:00"
at least one example should be without colons

2022-02-11 22:02 UTC, thearifismail commented on schemas/system_profile/v1.yaml
> +        example: "/dev/fdd0, /dev/fdd1, /dev/fdd2"
need some variety in disk devices.

2022-02-11 22:04 UTC, thearifismail commented on schemas/system_profile/v1.yaml
> +        example: "foo, bar, baz"
Should be some realistic names.  foo, bar, baz sound like function names.

2022-02-11 22:10 UTC, thearifismail commented on schemas/system_profile/v1.yaml
> +        example: "ARM, x86_64, null"
Can an arch value be "null"?

2022-02-14 17:00 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        example: "foo, bar, baz"
What would be a realistic name?

2022-02-14 17:15 UTC, ryandillinfelton commented on schemas/system_profile/v1.yaml
> +        example: "aws, ms, ibm"
We don't need every possibility to be an example

2022-02-15 14:05 UTC, kruai approved these changes

2022-02-15 14:51 UTC, thearifismail approved these changes

2022-02-15 14:51 UTC, thearifismail commented on schemas/system_profile/v1.yaml
> +        example: "foo, bar, baz"
Something from "ls -l /dev" would be better but not critical

2022-02-15 15:54 UTC, merged