Draft: feat: add releasever and basearch
RedHatInsights/inventory-schemas pull request #99
Opened 2022-11-03 16:27 UTC by vkrizan

Adds `releasever` and `basearch` facts to system profile gathered from `yum_updates`.

This is to properly identify YUM repository URLs. Especially those that have `$releasever` and `$basearch` placeholders.

Note, that these two facts are already present in `yum_updates` JSON. However, the `yum_updates` requires additional parsing, hence this information should be globally present on system profile.

VULN-2455

2022-11-04 11:46 UTC, strider commented
👍

2022-11-04 13:30 UTC, vkrizan commented on schemas/system_profile/v1.yaml
> +      basearch:
Looks like the `arch` should give the same result. `arch` comes from uname parser from some RPM package.

Let's also keep `basearch` as well to be sure that we use a proper value for repository URL substitutions.

2022-11-04 13:32 UTC, thearifismail commented on schemas/system_profile/v1.yaml
> +      releasever:
Aren't max lengths for releasever and basearch too long and making it easy to introduce mistakes?

2022-11-04 13:46 UTC, CodeHeeler requested changes
Found the typo causing failing validation

2022-11-04 13:46 UTC, CodeHeeler commented on schemas/system_profile/v1.yaml
> +        type: sting
typo here, type string not sting, that will fix the failing validation test

2022-11-04 13:47 UTC, CodeHeeler commented
ping @gmcculloug to get another stakeholder's feedback on naming and inclusion of new fields on sp schema.

2022-11-04 13:48 UTC, vkrizan commented on schemas/system_profile/v1.yaml
> +      releasever:
I've aligned the lengths to existing keys. `basearch` is aligned with `arch`s limit of 50, and `releasever` is aligned with `os_release`'s limit of 100.

2022-11-04 13:51 UTC, CodeHeeler commented on schemas/system_profile/v1.yaml
> +      releasever:
Valid feedback, though the same could be said for `arch` above, so I would say not a blocker.

2022-11-04 13:52 UTC, vkrizan commented on schemas/system_profile/v1.yaml
> +        type: sting
Fixed. Thank you!

2022-11-04 13:58 UTC, thearifismail approved these changes

2022-11-04 14:00 UTC, CodeHeeler approved these changes
LGTM, thanks!

2022-11-04 14:18 UTC, CodeHeeler commented
> @vkrizan Can you create a subtask on VULN-2404 similar to VULN-2447 to cover sync with hbi and xjoin? I'll create tasks for that in ESSNTL that you can link to like we did for mirrorlist.

ESSNTL-3672 & ESSNTL-3673 cover HBI and Xjoin

2022-11-04 14:53 UTC, vkrizan commented
> > @vkrizan Can you create a subtask on VULN-2404 similar to VULN-2447 to cover sync with hbi and xjoin? I'll create tasks for that in ESSNTL that you can link to like we did for mirrorlist.
> 
> ESSNTL-3672 & ESSNTL-3673 cover HBI and Xjoin

Done -> VULN-2461

2022-11-04 15:28 UTC, kruai approved these changes

2022-11-04 15:54 UTC, kruai reviewed
I've got a couple of questions, but we should probably rename these fields as well, since their names are fairly unclear. They should follow the standard we use in the rest of our fields (`release_version` and `base_arch`, for instance)

2022-11-04 15:54 UTC, kruai commented on schemas/system_profile/v1.yaml
> +      basearch:
@vkrizan Won't this effectively be duplicating the value? What makes `basearch` different from `arch`?

2022-11-04 15:54 UTC, kruai commented on schemas/system_profile/v1.yaml
> +      releasever:
Why does this need a new field rather than using an existing one like `os_release`?
I'm also unclear on what values we can expect... the name implies "release version", but the description says it's the release name, but then the examples look like version numbers (except 7server).

2022-11-04 18:44 UTC, thearifismail commented
> I've got a couple of questions, but we should probably rename these fields as well, since their names are fairly unclear. They should follow the standard we use in the rest of our fields (`release_version` and `base_arch`, for instance)

@kruai I had the same question and also wanted to understand if the their values could be different from within a system, so I snooped around and found this is `/etc/yum.repos.d/fedora.repo`. I guessed it was better to keep the names the same as they appeared in URLs
```
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
```

2022-11-04 19:07 UTC, CodeHeeler commented
> > I've got a couple of questions, but we should probably rename these fields as well, since their names are fairly unclear. They should follow the standard we use in the rest of our fields (`release_version` and `base_arch`, for instance)
> 
> @kruai I had the same question and also wanted to understand if the their values could be different from within a system, so I snooped around and found this is `/etc/yum.repos.d/fedora.repo`. I guessed it was better to keep the names the same as they appeared in URLs
> 
> ```
> metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
> ```

Yeah, I agreed with kruai's comment regarding the names not being in line with our usual expectations, but as vkrizan pointed out this was explicitly to provide the placeholders without further parsing of the yum repo json, and thearifismail's search corroborates this.

2022-11-07 08:46 UTC, vkrizan commented on schemas/system_profile/v1.yaml
> +      basearch:
My understanding of the `arch` is that it provides architecture whilst `basearch` provides **family** of the architecture. `arch` comes from `uname.arch`, whilst `basearch` comes from DNF/YUM. The difference between `arch` and `basearch` is mentioned in [dnf documentation](https://dnf.readthedocs.io/en/latest/api_conf.html#dnf.conf.Conf.substitutions), and the mapping can be found in the [dnf repository](https://github.com/rpm-software-management/dnf/blob/96b08be69050cddbc4c3abdd227bd28969249db9/dnf/rpm/__init__.py#L88-L115). This can be compared with [`KNOWN_ARCHITECTURES` from Insights client](https://github.com/RedHatInsights/insights-core/blob/084e85d10f6e5df575427cf602807b7172ecae12/insights/parsers/installed_rpms.py#L84-L139).

2022-11-07 08:56 UTC, vkrizan commented on schemas/system_profile/v1.yaml
> +      releasever:
`releasever` should be "release name of the system distribution" configured and/or detected by YUM/DNF. The value is affected by configuration and subscription manager, or otherwise detected. The detection is not easy to replicate, check implementation of [`detect_releasever` within dnf](https://github.com/rpm-software-management/dnf/blob/96b08be69050cddbc4c3abdd227bd28969249db9/dnf/rpm/__init__.py#L29-L70). Values depend on distribution and are created by Release Engineering.

On the other hand `os_release` is parsed out of `/etc/redhat-release` providing only a version part.

2022-11-07 08:57 UTC, vkrizan commented
For naming consistency with their source, I'd like to keep the names the same: `basearch` and `releasever`. That's how they are used and set within yum/dnf configuration.

2022-11-09 18:06 UTC, kruai commented
> Hello, is there more feedback?

As with the last PR, we need to run these by the stakeholders before we merge it. We have these meetings weekly, and the next one is today (in 25 mins). If nobody has any objections, I'll merge it

2022-11-09 19:48 UTC, merged